### ISSUE TITLE
Responsivity problems between different iPhone resolutions

### ISSUE THREAD

**Issue by gregballot** [kirualex/KASlideShow#17]
I put this amazing slideshow in my app yesterday, but when it comes to test it on the iPhone 6, the images did not took all the screen width. (The Slideshow view was filling the width thanks to the constraints but the images inside took something like 3/4 of the slideshow). I tried to scale programmatically but it doesn't work. I tried this : "slideShow.contentMode = UIViewContentMode.ScaleAspectFill" but it doesn't work too. 

Thanks for your attention !

**Comment by kirualex** [comment]
should be fixed

**Comment by gregballot** [comment]
It works, thanks !
