### ISSUE TITLE
Remove image from slideShow

### ISSUE THREAD

**Issue by gitabdelkarim** [kirualex/KASlideShow#22]
In my project i have a button to delete current image. So is it possible to remove an image from slideShow ? after deleting i will show the next image with : [_slideshow next];

**Comment by kirualex** [comment]
You'll have to try and get back to me on this

**Comment by gitabdelkarim** [comment]
Problem fixed, i added "deleteImageAtIndex:(NSUInteger) index" method

**Comment by kirualex** [comment]
don't hesitate to submit a pull request !
