### ISSUE TITLE
Not working with image URL

### ISSUE THREAD

**Issue by BhavinBhadani** [kirualex/KASlideShow#24]
Is this working with imageURL...because in my project it gives me error and i worked with every possible methods...

    [_slideshow setDelay:1]; // Delay between transitions
    [_slideshow setTransitionDuration:.5]; // Transition duration
    [_slideshow setTransitionType:KASlideShowTransitionFade]; // Choose a transition type (fade or slide)
    [_slideshow setImagesContentMode:UIViewContentModeScaleAspectFill]; // Choose a content mode for images to display.

    NSArray *imagelist = [imglist componentsSeparatedByString:@","];
    NSLog(@"%@",imagelist);
    [_slideshow emptyAndAddImagesFromResources:imagelist]; // Add images from resources
    _slideshow.gestureRecognizers = nil;
    [_slideshow addGesture:KASlideShowGestureSwipe]; // Gesture to go previous/next directly on the image
    [_slideshow start];

**Comment by kirualex** [comment]
No it doesn't. I recommend using `SDWebImage` to do so.

**Comment by benmore99** [comment]
try to use this,
```
[myslideshow addImage:[UIImage imageWithData:[NSData dataWithContentsOfURL:[NSURL URLWithString:img_path]]]]
```
