### ISSUE TITLE
My original images are zooming in on slideshow

### ISSUE THREAD

**Issue by sachinrot** [kirualex/KASlideShow#31]
Hello All,
this works perfectly for me except one small problem, my images which are downloaded from URL, are zoomed in when they apprear in slideshow. I know i can set this property in "setImagesContentMode" but trust me i tried all of them and nothing works, sometimes it only shows half the image, it doesnt show my image 100% in the frame of slideshow. can anyone please help me here.
I have added slideshow in storyboard and this is my code in my controller 
slideShow.images=[[NSMutableArray alloc]init];
    slideShow.delegate = self;
    [slideShow setDelay:2.0]; // Delay between transitions
    [slideShow setTransitionDuration:2.0]; // Transition duration
    [slideShow setTransitionType:KASlideShowTransitionSlide]; 
    [slideShow setImagesContentMode:UIViewContentModeScaleAspectFill]; 
    [slideShow addGesture:KASlideShowGestureAll];

the images are getting downloaded from my server and all i want is that slideshow should take my images and resize them so that it fits in the frame of slideshow 
i have tried all possible combinations in setImagesContentMode.
Thanks in advance 
Sachin

**Comment by kirualex** [comment]
Just tested with `UIViewContentModeScaleAspectFit`. It does work as intended, not sure where your issue is. Maybe try with last version.
