### ISSUE TITLE
Support For URL Loading

### ISSUE THREAD

**Issue by glennposadas** [kirualex/KASlideShow#38]
I found this repo on Github that has this enhancement feature for KASlideShow:
https://github.com/ad4n/KASlideShow-SDWebImage
If you could merge this functionality, it will be so great!

**Comment by kirualex** [comment]
Nice find, I think this would be nice as a subspec as I'd prefer for the library not to rely on too many dependencies. I'll look into it.

**Comment by glennposadas** [comment]
Actually @kirualex , the KASlideShow+SDWebImage I found and posted above works perfectly fine. I really love it, it has a caching feature and everything I need for my project. What I am asking you is, it would be great if it is possible for you to merge that ad4n's work into your work since you're already supporting cocoapods. I'm just wondering though why that guy didn't file a pull request. Anyway, thank you so much for this open source library.

G

**Comment by kirualex** [comment]
The issue is that I don't want KASlideShow pod to automatically download SDWebImage, as many people only use local images and may not appreciate having unnecessary dependencies. A subspec would make more sense, I'll have a look when I have time.

**Comment by samiq** [comment]
any update on this? I'd find it interesting how many people use this with local images vs web, as I'm sure most apps these days are dynamic and use content from the web in the great majority of cases. love the component by the way, it's just happens to add more work to keep the functionalities separate

**Comment by kirualex** [comment]
Implemented in 3.0.0

**Comment by samiq** [comment]
@kirualex thanks :)

**Comment by glennposadas** [comment]
Hot damn. Thank you so much. Now i dont need to re attach sdwebimage to my
pods everytime I do pod install or pod update.

Glenn
