### ISSUE TITLE
Keep things compatible with older versions

### ISSUE THREAD

**Issue by lucaseverini** [kirualex/KASlideShow#40]
Hello,
Is nice that you keep improving the frameworks but you should also consider to maintain compatibility with older versions.
Wasn't possible to keep the addImage method?

**Comment by kirualex** [comment]
I'm using semantic versioning on this library. 3.0.0 was a major update, hence the braking changes. You can stay on 2.x if you need they API to remain the same though, via `pod "KASlideShow", "~> 2.0"`
