### ISSUE TITLE
KASlideShow fails to autoslide - nil self.window blocks animation 

### ISSUE THREAD

**Issue by teffi** [kirualex/KASlideShow#43]
`if (!self.window) return;` could return nil if view is not added in a view controller directly

`self.superview` might be more appropriate.

Those who are having this issue, temporarily replace`if (!self.window) return;` with `if (!self.superview) return;` instead. Not sure if this have side effects for now.

**Comment by zh-wowtv** [comment]
Sometimes self.superview is nil although it's a child of a view. I just remove this to solve the problem.
