### ISSUE TITLE
Images with Transparent Background Appear in White

### ISSUE THREAD

**Issue by OmarAlEisa** [kirualex/KASlideShow#45]
When using a PNG image with a transparent background, the slideshow view background turns into white. Here's a screenshot to show what actually happens (left) vs. what should happen (right).

![simulator screen shot oct 24 2016 6 20 19 pm](https://cloud.githubusercontent.com/assets/7313080/19671064/f4fbcdd0-9a20-11e6-8022-d785fbd5b88b.png)

**More info:**
Right now, I'm temporarily fixing this by manually changing the background color of one of the subviews of _slideshow to grey (discovered this by trial and error).

`_slideshow.subviews[1].backgroundColor = [UIColor colorWithRed:232.0/255.0 green:232.0/255.0 blue:232.0/255.0 alpha:1.0];`

At first I tried setting the background color to [UIColor clearColor], but the problem was that before starting the slideshow, it shows the slides staked on top of each other.

**Comment by alexiscreuzot** [comment]
With commit 3e46e9064b28d2c1ca2721d3ddf7da164c9edc5b , the UIImageViews background are now using the same background as their superview. This should solve this issue.
