### ISSUE TITLE
Only KASlideShowGestureSwipe some how not working - Xcode8

### ISSUE THREAD

**Issue by saad-ansari** [kirualex/KASlideShow#46]
Only KASlideShowGestureSwipe some how not working rest is fine!!
Please advise if i'm missing some thing!!

_datasource = [@[[NSURL URLWithString:detailDic[@"image1"]],
                     [NSURL URLWithString:detailDic[@"image2"]]]mutableCopy];
    
    // KASlideshow
    _slideShow.datasource = self;
    _slideShow.delegate = self;
    [_slideShow setDelay:5]; // Delay between transitions
    [_slideShow setTransitionDuration:.5]; // Transition duration
    [_slideShow setTransitionType:KASlideShowTransitionSlideHorizontal]; // Choose a transition type (fade or slide)
    [_slideShow setImagesContentMode:UIViewContentModeScaleAspectFill]; // Choose a content mode for images to display
    [_slideShow addGesture:KASlideShowGestureSwipe]; // Gesture to go previous/next directly on the image
    dispatch_after(dispatch_time(DISPATCH_TIME_NOW, 4 * NSEC_PER_SEC), dispatch_get_main_queue(), ^{
        [_slideShow start];
    });

**Comment by hamidghasemy** [comment]
you have to set TransitionType to KASlideShowTransitionSlideHorizontal
thats work !
