### ISSUE TITLE
Dynamic loading of images in KASlideShow

### ISSUE THREAD

**Issue by chetanpanchal94** [kirualex/KASlideShow#49]
The problem is that I see the photos at index 0 only after I make an initial swipe on the UIView.

- (NSObject *)slideShow:(KASlideShow *)slideShow objectAtIndex:(NSUInteger)index {    
    self.objOffer = offersAvailable[index];
    return [NSURL URLWithString:self.objOffer.imageURL];
}

**Comment by kirualex** [comment]
Maybe try the pod from the git repo (pod 'KASlideShow', :git => 'https://github.com/kirualex/KASlideShow/'), and use `reloadData` method once your image is loaded.

**Comment by chetanpanchal94** [comment]
hey kirualex,

I have installed kaslidShow through pods, int its .h file i am not getting this method:
- (NSObject *) slideShow:(KASlideShow *)slideShow objectAtIndex:(NSUInteger)index;

**Comment by kirualex** [comment]
documentation is only valid for last version, 3.0
