### ISSUE TITLE
tap on action image

### ISSUE THREAD

**Issue by PrakashMaharjan** [kirualex/KASlideShow#56]
is there delegate to get tapped index/image in image??

**Comment by kirualex** [comment]
you can basically add a tap gesture on the slideshow and get its current index in your handling method.

**Comment by PrakashMaharjan** [comment]
Not sure exactly, as there is already a tap gesture defined in code as KASlideShowGestureTap so it triggers previous and next slide.
[_slideshow addGesture:KASlideShowGestureTap]; // Gesture to go previous/next directly on the image
}
Anyway, thanks for response.
