### ISSUE TITLE
Move to specific index

### ISSUE THREAD

**Issue by docash59** [kirualex/KASlideShow#58]
Is there a way we could jump to a specific slide index?
Like from index 0 and jump to 4 (with the slideshow set to pause of course)

**Comment by alexiscreuzot** [comment]
This should be possible by making `currentIndex ` read-writable instead of readonly. Maybe a better way would be to add a function to jump to a specific index.

**Comment by alexiscreuzot** [comment]
I implemented this feature with the method : 
```objective-c
- (void) jumpTo:(NSUInteger) index direction:(KASlideShowDirection) direction;
```
The second parameter is only important in case the slideshow is in slide mode.

**Comment by docash59** [comment]
Awesome thank you!
