### ISSUE TITLE
Ability to perform action upon tapping on slide index

### ISSUE THREAD

**Issue by docash59** [kirualex/KASlideShow#59]
I know the library already has the Tap and Slide gesture but that is to advance the slideshow to next one.
However, Im talking about performing an action like tapping on current index and opens a URL or something. Adding this would be great!

**Comment by alexiscreuzot** [comment]
This is already possible with something like this : 
```objective-c
UITapGestureRecognizer * tap = [[UITapGestureRecognizer alloc] initWithTarget:self 
action:@selector(__your_method__)];
tap.delegate = self;
[self.slideshow addGestureRecognizer:tap];
```
Just don't forget to implement the `delegate` likeso : 
```objective-c
- (BOOL)gestureRecognizer:(UIGestureRecognizer *)gestureRecognizer shouldRecognizeSimultaneouslyWithGestureRecognizer:(UIGestureRecognizer *)otherGestureRecognizer {
    return true;
}
```
